apiVersion: v1
kind: Service

metadata:
  name: api
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
  
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: container-port

    - name: metrics
      port: 8081
      protocol: TCP
      targetPort: metrics

  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: microservice