# apiVersion: v1
# kind: Service

# metadata:
#   name: api
#   namespace: default
#   annotations:
#     cloud.google.com/neg: '{"ingress": true}'
#     # cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
  
# spec:
#   type: ClusterIP
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: container-port

#     - name: metrics
#       port: 8081
#       protocol: TCP
#       targetPort: metrics

#   selector:
#     app.kubernetes.io/name: api
#     app.kubernetes.io/component: microservice


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-pod
        image: arungupta/helloworld-spring-boot:latest
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  