apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-test
spec:
  replicas: 1 
  selector:
    matchLabels:
        app: hello-world-test
  template:
    metadata:
      labels:
        app: hello-world-test
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-test
spec:
  selector:
    app: hello-world-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80